import type { AuditLogEntry } from './types'

/** Static mock rows for fund admin audit log until subgraph is wired (server + API route). */
export const MOCK_AUDIT_LOG_ENTRIES: AuditLogEntry[] = [
  {
    id: '1',
    date: 'Feb 24, 2026',
    action: 'Paused deposits',
    valueReason: 'Paused because of blablabla...',
    tokenAmount: null,
    usdAmount: null,
    user: 'Admin',
  },
  {
    id: '2',
    date: 'Feb 23, 2026',
    action: 'Resumed deposits',
    valueReason: null,
    tokenAmount: null,
    usdAmount: null,
    user: 'Admin',
  },
  {
    id: '3',
    date: 'Feb 22, 2026',
    action: 'NAV updated',
    valueReason: null,
    tokenAmount: '999,999,999',
    usdAmount: '282.00',
    user: 'Fund Manager',
  },
  {
    id: '4',
    date: 'Feb 1, 2026',
    action: 'Top Up Synthethic Yield',
    valueReason: null,
    tokenAmount: '999,999,999',
    usdAmount: '282.00',
    user: 'Fund Manager',
  },
  {
    id: '5',
    date: 'Feb 1, 2026',
    action: 'Transfer to Manager Wallet',
    valueReason: null,
    tokenAmount: '999,999,999',
    usdAmount: '282.00',
    user: 'Fund Manager',
  },
  {
    id: '6',
    date: 'Jan 28, 2026',
    action: 'Changed withdrawal limits',
    valueReason: 'Quarterly policy update',
    tokenAmount: null,
    usdAmount: null,
    user: 'Admin',
  },
  {
    id: '7',
    date: 'Jan 15, 2026',
    action: 'Distributed rewards',
    valueReason: null,
    tokenAmount: '500,000',
    usdAmount: '140.00',
    user: 'Fund Manager',
  },
  {
    id: '8',
    date: 'Jan 10, 2026',
    action: 'Updated portfolio allocation',
    valueReason: 'Rebalanced to 60/40',
    tokenAmount: null,
    usdAmount: null,
    user: 'Fund Manager',
  },
  {
    id: '9',
    date: 'Jan 2, 2026',
    action: 'Added new asset',
    valueReason: 'Approved by governance',
    tokenAmount: null,
    usdAmount: null,
    user: 'Admin',
  },
  {
    id: '10',
    date: 'Dec 31, 2025',
    action: 'Year end audit completed',
    valueReason: 'No discrepancies found',
    tokenAmount: null,
    usdAmount: null,
    user: 'Fund Manager',
  },
]
