export { Description } from './Description'
export { ProposalDetails } from './ProposalDetails'
export { ProposalProggressBar } from './ProposalProggressBar'
export { TechnicalDetails } from './TechnicalDetails'
export { VotingDetails } from './VotingDetails'
