/** Tooltip copy for each capital allocation category in the undetailed view. */
export const CAPITAL_ALLOCATION_TOOLTIP_MAP: Record<string, string> = {
  'Deployed capital': 'Capital currently deployed to yield-generating strategies',
  'Liquidity reserve': 'Capital held in reserve for withdrawal liquidity',
  'Unallocated capital': 'Capital not yet allocated to any strategy',
}

/** Tooltips for the Contract Addresses subsection in the capital allocation section. */
export const CONTRACT_ADDRESSES_TOOLTIP_MAP = {
  vaultAddress: 'The smart contract address of the BTC vault holding deposited rBTC.',
  shareTokenContract:
    'The ERC-20 share token contract; you receive these tokens when you deposit and redeem them when you withdraw.',
} as const

/** Tooltips for the Fees Info subsection in the capital allocation section. */
export const FEES_INFO_TOOLTIP_MAP = {
  depositFee: 'Percentage charged on deposits when you add rBTC to the vault.',
  redemptionFee: 'Percentage charged when you redeem vault shares for rBTC.',
  annualManagementFee: 'Yearly fee charged on assets under management.',
  performanceFee: 'Fee charged on yield generated by the vault strategies.',
} as const

/**
 * Placeholder fee percentages for display until contract/API provides them.
 * Values are percentage strings (e.g. "15%").
 */
export const FEES_INFO_PLACEHOLDER: Record<keyof typeof FEES_INFO_TOOLTIP_MAP, string> = {
  depositFee: '15%',
  redemptionFee: '15%',
  annualManagementFee: '15%',
  performanceFee: '15%',
}
