const COLUMN_ID = 'id'
const REWARDS_RIF = 'rewardsRif'
const REWARDS_RBTC = 'rewardsRBTC'
const CURRENT_CYCLE_START = 'currentCycleStart'
const CURRENT_CYCLE_DURATION = 'currentCycleDuration'
const PREVIOUS_CYCLE_START = 'previousCycleStart'
const PREVIOUS_CYCLE_DURATION = 'previousCycleDuration'
const DISTRIBUTION_DURATION = 'distributionDuration'
const ON_DISTRIBUTION_PERIOD = 'onDistributionPeriod'

export const CYCLE_COLUMNS = [
  COLUMN_ID,
  REWARDS_RIF,
  REWARDS_RBTC,
  CURRENT_CYCLE_START,
  CURRENT_CYCLE_DURATION,
  PREVIOUS_CYCLE_START,
  PREVIOUS_CYCLE_DURATION,
  DISTRIBUTION_DURATION,
  ON_DISTRIBUTION_PERIOD,
]

const ALLOCATIONS_DAILY_COLUMN_DAY = 'day'
const ALLOCATIONS_DAILY_COLUMN_TOTAL_ALLOCATION = 'totalAllocation'

export const ALLOCATIONS_DAILY_COLUMNS = [
  COLUMN_ID,
  ALLOCATIONS_DAILY_COLUMN_DAY,
  ALLOCATIONS_DAILY_COLUMN_TOTAL_ALLOCATION,
]
