const COLUMN_ID = 'id'

const CURRENT_CYCLE_START = 'currentCycleStart'
const CURRENT_CYCLE_DURATION = 'currentCycleDuration'
const PREVIOUS_CYCLE_START = 'previousCycleStart'
const PREVIOUS_CYCLE_DURATION = 'previousCycleDuration'
const DISTRIBUTION_DURATION = 'distributionDuration'
const ON_DISTRIBUTION_PERIOD = 'onDistributionPeriod'

export const CYCLE_COLUMNS = [
  `Cycle.${COLUMN_ID}`,
  CURRENT_CYCLE_START,
  CURRENT_CYCLE_DURATION,
  PREVIOUS_CYCLE_START,
  PREVIOUS_CYCLE_DURATION,
  DISTRIBUTION_DURATION,
  ON_DISTRIBUTION_PERIOD,
]

const ALLOCATIONS_DAILY_COLUMN_DAY = 'day'
const ALLOCATIONS_DAILY_COLUMN_TOTAL_ALLOCATION = 'totalAllocation'

export const ALLOCATIONS_DAILY_COLUMNS = [
  COLUMN_ID,
  ALLOCATIONS_DAILY_COLUMN_DAY,
  ALLOCATIONS_DAILY_COLUMN_TOTAL_ALLOCATION,
]

const TX_HISTORY_TYPE = 'type'
const TX_HISTORY_CYCLE_START = 'cycleStart'
const TX_HISTORY_BLOCK_HASH = 'blockHash'
const TX_HISTORY_BACKER = 'backer'
const TX_HISTORY_BUILDER = 'builder'
const TX_HISTORY_ALLOCATION = 'allocation'
const TX_HISTORY_AMOUNT = 'amount'
const TX_HISTORY_BLOCK_TIMESTAMP = 'blockTimestamp'
const TX_HISTORY_INCREASED = 'increased'
const TX_HISTORY_REWARD_TOKEN = 'rewardToken'
const TX_HISTORY_TOTAL_AMOUNT = 'totalAmount'
const TX_HISTORY_TRANSACTION_HASH = 'transactionHash'

export const TX_HISTORY_COLUMNS = [
  COLUMN_ID,
  TX_HISTORY_TYPE,
  TX_HISTORY_BACKER,
  TX_HISTORY_BUILDER,
  TX_HISTORY_BLOCK_HASH,
  TX_HISTORY_BLOCK_TIMESTAMP,
  TX_HISTORY_CYCLE_START,
  TX_HISTORY_TRANSACTION_HASH,
  TX_HISTORY_AMOUNT,
  TX_HISTORY_ALLOCATION,
  TX_HISTORY_INCREASED,
  TX_HISTORY_REWARD_TOKEN,
  TX_HISTORY_TOTAL_AMOUNT,
]

const BACKER_TO_BUILDER_BACKER = 'backer'
const BACKER_TO_BUILDER_BUILDER = 'builder'
const BACKER_TO_BUILDER_TOTAL_ALLOCATION = 'totalAllocation'
export const BACKER_TO_BUILDER_COLUMNS = [
  COLUMN_ID,
  BACKER_TO_BUILDER_BACKER,
  BACKER_TO_BUILDER_BUILDER,
  BACKER_TO_BUILDER_TOTAL_ALLOCATION,
]
