const COLUMN_ID = 'id'
const REWARDS_ERC20 = 'rewardsERC20'
const REWARDS_RBTC = 'rewardsRBTC'
const CYCLE_START = 'cycleStart'
const CYCLE_DURATION = 'cycleDuration'
const DISTRIBUTION_DURATION = 'distributionDuration'
const ON_DISTRIBUTION_PERIOD = 'onDistributionPeriod'

export const CYCLE_COLUMNS = [
  COLUMN_ID,
  REWARDS_ERC20,
  REWARDS_RBTC,
  CYCLE_START,
  CYCLE_DURATION,
  DISTRIBUTION_DURATION,
  ON_DISTRIBUTION_PERIOD,
]

const ALLOCATIONS_DAILY_COLUMN_DAY = 'day'
const ALLOCATIONS_DAILY_COLUMN_TOTAL_ALLOCATION = 'totalAllocation'

export const ALLOCATIONS_DAILY_COLUMNS = [
  COLUMN_ID,
  ALLOCATIONS_DAILY_COLUMN_DAY,
  ALLOCATIONS_DAILY_COLUMN_TOTAL_ALLOCATION,
]
