export const RBTCAsyncVaultAbi = [
  {
    type: 'constructor',
    inputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'error',
    name: 'AddressEmptyCode',
    inputs: [{ name: 'target', type: 'address', internalType: 'address' }],
  },
  {
    type: 'error',
    name: 'AsyncFlow',
  },
  {
    type: 'error',
    name: 'CannotSetSelfAsOperator',
  },
  {
    type: 'error',
    name: 'ClaimExceedsAvailable',
  },
  {
    type: 'error',
    name: 'DepositActivePrevEpoch',
  },
  {
    type: 'error',
    name: 'DepositNotAccepted',
  },
  {
    type: 'error',
    name: 'DepositNotPending',
  },
  {
    type: 'error',
    name: 'DepositRequestsPaused',
  },
  {
    type: 'error',
    name: 'ERC1967InvalidImplementation',
    inputs: [{ name: 'implementation', type: 'address', internalType: 'address' }],
  },
  {
    type: 'error',
    name: 'ERC1967NonPayable',
  },
  {
    type: 'error',
    name: 'ERC20InsufficientAllowance',
    inputs: [
      { name: 'spender', type: 'address', internalType: 'address' },
      { name: 'allowance', type: 'uint256', internalType: 'uint256' },
      { name: 'needed', type: 'uint256', internalType: 'uint256' },
    ],
  },
  {
    type: 'error',
    name: 'ERC20InsufficientBalance',
    inputs: [
      { name: 'sender', type: 'address', internalType: 'address' },
      { name: 'balance', type: 'uint256', internalType: 'uint256' },
      { name: 'needed', type: 'uint256', internalType: 'uint256' },
    ],
  },
  {
    type: 'error',
    name: 'ERC20InvalidApprover',
    inputs: [{ name: 'approver', type: 'address', internalType: 'address' }],
  },
  {
    type: 'error',
    name: 'ERC20InvalidReceiver',
    inputs: [{ name: 'receiver', type: 'address', internalType: 'address' }],
  },
  {
    type: 'error',
    name: 'ERC20InvalidSender',
    inputs: [{ name: 'sender', type: 'address', internalType: 'address' }],
  },
  {
    type: 'error',
    name: 'ERC20InvalidSpender',
    inputs: [{ name: 'spender', type: 'address', internalType: 'address' }],
  },
  {
    type: 'error',
    name: 'ERC4626ExceededMaxDeposit',
    inputs: [
      { name: 'receiver', type: 'address', internalType: 'address' },
      { name: 'assets', type: 'uint256', internalType: 'uint256' },
      { name: 'max', type: 'uint256', internalType: 'uint256' },
    ],
  },
  {
    type: 'error',
    name: 'ERC4626ExceededMaxMint',
    inputs: [
      { name: 'receiver', type: 'address', internalType: 'address' },
      { name: 'shares', type: 'uint256', internalType: 'uint256' },
      { name: 'max', type: 'uint256', internalType: 'uint256' },
    ],
  },
  {
    type: 'error',
    name: 'ERC4626ExceededMaxRedeem',
    inputs: [
      { name: 'owner', type: 'address', internalType: 'address' },
      { name: 'shares', type: 'uint256', internalType: 'uint256' },
      { name: 'max', type: 'uint256', internalType: 'uint256' },
    ],
  },
  {
    type: 'error',
    name: 'ERC4626ExceededMaxWithdraw',
    inputs: [
      { name: 'owner', type: 'address', internalType: 'address' },
      { name: 'assets', type: 'uint256', internalType: 'uint256' },
      { name: 'max', type: 'uint256', internalType: 'uint256' },
    ],
  },
  {
    type: 'error',
    name: 'FailedCall',
  },
  {
    type: 'error',
    name: 'InsufficientFreeOnchainLiquidity',
  },
  {
    type: 'error',
    name: 'InvalidCaller',
  },
  {
    type: 'error',
    name: 'InvalidInitialization',
  },
  {
    type: 'error',
    name: 'InvalidState',
  },
  {
    type: 'error',
    name: 'NativeTransferFailed',
  },
  {
    type: 'error',
    name: 'NoDepositRequest',
  },
  {
    type: 'error',
    name: 'NoRedeemRequest',
  },
  {
    type: 'error',
    name: 'NotInitializing',
  },
  {
    type: 'error',
    name: 'OffchainAssetsInsufficient',
  },
  {
    type: 'error',
    name: 'PartialClaimNotAllowed',
  },
  {
    type: 'error',
    name: 'RedeemActivePrevEpoch',
  },
  {
    type: 'error',
    name: 'RedeemNotClaimable',
  },
  {
    type: 'error',
    name: 'RedeemNotPending',
  },
  {
    type: 'error',
    name: 'RedeemRequestsPaused',
  },
  {
    type: 'error',
    name: 'ReentrancyGuardReentrantCall',
  },
  {
    type: 'error',
    name: 'SafeERC20FailedOperation',
    inputs: [{ name: 'token', type: 'address', internalType: 'address' }],
  },
  {
    type: 'error',
    name: 'UUPSUnauthorizedCallContext',
  },
  {
    type: 'error',
    name: 'UUPSUnsupportedProxiableUUID',
    inputs: [{ name: 'slot', type: 'bytes32', internalType: 'bytes32' }],
  },
  {
    type: 'error',
    name: 'UnexpectedNativeTransfer',
  },
  {
    type: 'error',
    name: 'ZeroAddress',
  },
  {
    type: 'error',
    name: 'ZeroValue',
  },
  {
    type: 'event',
    name: 'Approval',
    inputs: [
      { name: 'owner', indexed: true, type: 'address', internalType: 'address' },
      { name: 'spender', indexed: true, type: 'address', internalType: 'address' },
      { name: 'value', indexed: false, type: 'uint256', internalType: 'uint256' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'BufferSet',
    inputs: [
      { name: 'previousBuffer', indexed: true, type: 'address', internalType: 'address' },
      { name: 'newBuffer', indexed: true, type: 'address', internalType: 'address' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'CapitalDeployed',
    inputs: [
      { name: 'destination', indexed: true, type: 'address', internalType: 'address' },
      { name: 'assets', indexed: false, type: 'uint256', internalType: 'uint256' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'CapitalReturned',
    inputs: [
      { name: 'from', indexed: true, type: 'address', internalType: 'address' },
      { name: 'assets', indexed: false, type: 'uint256', internalType: 'uint256' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'Deposit',
    inputs: [
      { name: 'sender', indexed: true, type: 'address', internalType: 'address' },
      { name: 'owner', indexed: true, type: 'address', internalType: 'address' },
      { name: 'assets', indexed: false, type: 'uint256', internalType: 'uint256' },
      { name: 'shares', indexed: false, type: 'uint256', internalType: 'uint256' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'DepositClaimed',
    inputs: [
      { name: 'caller', indexed: true, type: 'address', internalType: 'address' },
      { name: 'controller', indexed: true, type: 'address', internalType: 'address' },
      { name: 'receiver', indexed: true, type: 'address', internalType: 'address' },
      { name: 'epochId', indexed: false, type: 'uint256', internalType: 'uint256' },
      { name: 'assets', indexed: false, type: 'uint256', internalType: 'uint256' },
      { name: 'shares', indexed: false, type: 'uint256', internalType: 'uint256' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'DepositRequest',
    inputs: [
      { name: 'controller', indexed: true, type: 'address', internalType: 'address' },
      { name: 'owner', indexed: true, type: 'address', internalType: 'address' },
      { name: 'requestId', indexed: true, type: 'uint256', internalType: 'uint256' },
      { name: 'sender', indexed: false, type: 'address', internalType: 'address' },
      { name: 'assets', indexed: false, type: 'uint256', internalType: 'uint256' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'DepositRequestCancelled',
    inputs: [
      { name: 'controller', indexed: true, type: 'address', internalType: 'address' },
      { name: 'receiver', indexed: true, type: 'address', internalType: 'address' },
      { name: 'requestId', indexed: true, type: 'uint256', internalType: 'uint256' },
      { name: 'assets', indexed: false, type: 'uint256', internalType: 'uint256' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'DepositRequestsPausedSet',
    inputs: [
      { name: 'previousPaused', indexed: false, type: 'bool', internalType: 'bool' },
      { name: 'newPaused', indexed: false, type: 'bool', internalType: 'bool' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'EpochFundingProgress',
    inputs: [
      { name: 'epochId', indexed: true, type: 'uint256', internalType: 'uint256' },
      { name: 'fundedAssets', indexed: false, type: 'uint256', internalType: 'uint256' },
      { name: 'requiredAssets', indexed: false, type: 'uint256', internalType: 'uint256' },
      { name: 'claimable', indexed: false, type: 'bool', internalType: 'bool' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'EpochSettled',
    inputs: [
      { name: 'epochId', indexed: true, type: 'uint256', internalType: 'uint256' },
      { name: 'reportedOffchainAssets', indexed: false, type: 'uint256', internalType: 'uint256' },
      { name: 'assets', indexed: false, type: 'uint256', internalType: 'uint256' },
      { name: 'supply', indexed: false, type: 'uint256', internalType: 'uint256' },
      { name: 'closedAt', indexed: false, type: 'uint64', internalType: 'uint64' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'FundingCursorAdvanced',
    inputs: [
      { name: 'previousEpochId', indexed: true, type: 'uint256', internalType: 'uint256' },
      { name: 'newEpochId', indexed: true, type: 'uint256', internalType: 'uint256' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'Initialized',
    inputs: [{ name: 'version', indexed: false, type: 'uint64', internalType: 'uint64' }],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'MaxFundingEpochsPerCallSet',
    inputs: [
      { name: 'previousMaxEpochs', indexed: false, type: 'uint256', internalType: 'uint256' },
      { name: 'newMaxEpochs', indexed: false, type: 'uint256', internalType: 'uint256' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'NativeDepositRequestCancelled',
    inputs: [
      { name: 'receiver', indexed: true, type: 'address', internalType: 'address' },
      { name: 'controller', indexed: true, type: 'address', internalType: 'address' },
      { name: 'requestId', indexed: true, type: 'uint256', internalType: 'uint256' },
      { name: 'assets', indexed: false, type: 'uint256', internalType: 'uint256' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'NativeDepositRequested',
    inputs: [
      { name: 'controller', indexed: true, type: 'address', internalType: 'address' },
      { name: 'owner', indexed: true, type: 'address', internalType: 'address' },
      { name: 'requestId', indexed: true, type: 'uint256', internalType: 'uint256' },
      { name: 'assets', indexed: false, type: 'uint256', internalType: 'uint256' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'OffchainAssetsAdjusted',
    inputs: [
      { name: 'previousReportedOffchainAssets', indexed: false, type: 'uint256', internalType: 'uint256' },
      { name: 'newReportedOffchainAssets', indexed: false, type: 'uint256', internalType: 'uint256' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'OffchainAssetsReported',
    inputs: [
      { name: 'reportedOffchainAssets', indexed: false, type: 'uint256', internalType: 'uint256' },
      { name: 'newEpochId', indexed: true, type: 'uint256', internalType: 'uint256' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'OperatorSet',
    inputs: [
      { name: 'controller', indexed: true, type: 'address', internalType: 'address' },
      { name: 'operator', indexed: true, type: 'address', internalType: 'address' },
      { name: 'approved', indexed: false, type: 'bool', internalType: 'bool' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'RedeemClaimed',
    inputs: [
      { name: 'caller', indexed: true, type: 'address', internalType: 'address' },
      { name: 'controller', indexed: true, type: 'address', internalType: 'address' },
      { name: 'receiver', indexed: true, type: 'address', internalType: 'address' },
      { name: 'epochId', indexed: false, type: 'uint256', internalType: 'uint256' },
      { name: 'assetOut', indexed: false, type: 'address', internalType: 'address' },
      { name: 'assets', indexed: false, type: 'uint256', internalType: 'uint256' },
      { name: 'shares', indexed: false, type: 'uint256', internalType: 'uint256' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'RedeemRequest',
    inputs: [
      { name: 'controller', indexed: true, type: 'address', internalType: 'address' },
      { name: 'owner', indexed: true, type: 'address', internalType: 'address' },
      { name: 'requestId', indexed: true, type: 'uint256', internalType: 'uint256' },
      { name: 'sender', indexed: false, type: 'address', internalType: 'address' },
      { name: 'shares', indexed: false, type: 'uint256', internalType: 'uint256' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'RedeemRequestCancelled',
    inputs: [
      { name: 'controller', indexed: true, type: 'address', internalType: 'address' },
      { name: 'receiver', indexed: true, type: 'address', internalType: 'address' },
      { name: 'requestId', indexed: true, type: 'uint256', internalType: 'uint256' },
      { name: 'shares', indexed: false, type: 'uint256', internalType: 'uint256' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'RedeemRequestsPausedSet',
    inputs: [
      { name: 'previousPaused', indexed: false, type: 'bool', internalType: 'bool' },
      { name: 'newPaused', indexed: false, type: 'bool', internalType: 'bool' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'SyntheticYieldApplied',
    inputs: [
      { name: 'epochId', indexed: true, type: 'uint256', internalType: 'uint256' },
      { name: 'syntheticYield', indexed: true, type: 'address', internalType: 'address' },
      { name: 'assetsAdded', indexed: false, type: 'uint256', internalType: 'uint256' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'SyntheticYieldSet',
    inputs: [
      { name: 'previousSyntheticYield', indexed: true, type: 'address', internalType: 'address' },
      { name: 'newSyntheticYield', indexed: true, type: 'address', internalType: 'address' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'Transfer',
    inputs: [
      { name: 'from', indexed: true, type: 'address', internalType: 'address' },
      { name: 'to', indexed: true, type: 'address', internalType: 'address' },
      { name: 'value', indexed: false, type: 'uint256', internalType: 'uint256' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'Upgraded',
    inputs: [{ name: 'implementation', indexed: true, type: 'address', internalType: 'address' }],
    anonymous: false,
  },
  {
    type: 'function',
    name: 'DECIMALS_OFFSET',
    outputs: [{ name: '', type: 'uint8', internalType: 'uint8' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'UPGRADE_INTERFACE_VERSION',
    outputs: [{ name: '', type: 'string', internalType: 'string' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'acceptanceEpoch',
    inputs: [{ name: 'controller', type: 'address', internalType: 'address' }],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'allowance',
    inputs: [
      { name: 'owner', type: 'address', internalType: 'address' },
      { name: 'spender', type: 'address', internalType: 'address' },
    ],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'approve',
    inputs: [
      { name: 'spender', type: 'address', internalType: 'address' },
      { name: 'value', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'asset',
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'balanceOf',
    inputs: [{ name: 'account', type: 'address', internalType: 'address' }],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'buffer',
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'cancelDepositRequest',
    inputs: [
      { name: 'requestId', type: 'uint256', internalType: 'uint256' },
      { name: 'controller', type: 'address', internalType: 'address' },
      { name: 'receiver', type: 'address', internalType: 'address' },
    ],
    outputs: [{ name: 'assetsRefunded', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'cancelDepositRequestNative',
    inputs: [
      { name: 'requestId', type: 'uint256', internalType: 'uint256' },
      { name: 'controller', type: 'address', internalType: 'address' },
      { name: 'receiver', type: 'address', internalType: 'address payable' },
    ],
    outputs: [{ name: 'assetsRefunded', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'cancelRedeemRequest',
    inputs: [
      { name: 'requestId', type: 'uint256', internalType: 'uint256' },
      { name: 'controller', type: 'address', internalType: 'address' },
      { name: 'receiver', type: 'address', internalType: 'address' },
    ],
    outputs: [{ name: 'sharesReturned', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'claimableDepositRequest',
    inputs: [
      { name: 'requestId', type: 'uint256', internalType: 'uint256' },
      { name: 'controller', type: 'address', internalType: 'address' },
    ],
    outputs: [{ name: 'claimableAssets', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'claimableRedeemRequest',
    inputs: [
      { name: 'requestId', type: 'uint256', internalType: 'uint256' },
      { name: 'controller', type: 'address', internalType: 'address' },
    ],
    outputs: [{ name: 'claimableShares', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'convertToAssets',
    inputs: [{ name: 'shares', type: 'uint256', internalType: 'uint256' }],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'convertToShares',
    inputs: [{ name: 'assets', type: 'uint256', internalType: 'uint256' }],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'currentEpoch',
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'decimals',
    outputs: [{ name: '', type: 'uint8', internalType: 'uint8' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'deposit',
    inputs: [
      { name: 'assets', type: 'uint256', internalType: 'uint256' },
      { name: 'receiver', type: 'address', internalType: 'address' },
      { name: 'controller', type: 'address', internalType: 'address' },
    ],
    outputs: [{ name: 'shares', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'deposit',
    inputs: [
      { name: 'assets', type: 'uint256', internalType: 'uint256' },
      { name: 'receiver', type: 'address', internalType: 'address' },
    ],
    outputs: [{ name: 'shares', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'depositReq',
    inputs: [{ name: 'controller', type: 'address', internalType: 'address' }],
    outputs: [
      { name: 'epochId', type: 'uint256', internalType: 'uint256' },
      { name: 'assets', type: 'uint256', internalType: 'uint256' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'depositRequestsPaused',
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'epochClosedAt',
    inputs: [{ name: 'epochId', type: 'uint256', internalType: 'uint256' }],
    outputs: [{ name: 'closedAt', type: 'uint64', internalType: 'uint64' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'epochRedeemClaimable',
    inputs: [{ name: 'epochId', type: 'uint256', internalType: 'uint256' }],
    outputs: [{ name: 'claimable', type: 'bool', internalType: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'epochRedeemFundedAssets',
    inputs: [{ name: 'epochId', type: 'uint256', internalType: 'uint256' }],
    outputs: [{ name: 'fundedAssets', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'epochRedeemRequiredAssets',
    inputs: [{ name: 'epochId', type: 'uint256', internalType: 'uint256' }],
    outputs: [{ name: 'requiredAssets', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'epochSnapshot',
    inputs: [{ name: 'epochId', type: 'uint256', internalType: 'uint256' }],
    outputs: [
      { name: 'closedAt', type: 'uint64', internalType: 'uint64' },
      { name: 'assetsAtClose', type: 'uint256', internalType: 'uint256' },
      { name: 'supplyAtClose', type: 'uint256', internalType: 'uint256' },
      { name: 'syntheticAddedAssets', type: 'uint256', internalType: 'uint256' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'epochSyntheticYieldAssets',
    inputs: [{ name: 'epochId', type: 'uint256', internalType: 'uint256' }],
    outputs: [{ name: 'assetsAdded', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'epochTotalAssets',
    inputs: [{ name: 'epochId', type: 'uint256', internalType: 'uint256' }],
    outputs: [{ name: 'assetsAtClose', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'epochTotalRedeemShares',
    inputs: [{ name: 'epochId', type: 'uint256', internalType: 'uint256' }],
    outputs: [{ name: 'totalShares', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'epochTotalSupply',
    inputs: [{ name: 'epochId', type: 'uint256', internalType: 'uint256' }],
    outputs: [{ name: 'supplyAtClose', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'freeOnchainLiquidity',
    outputs: [{ name: 'free', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'initialize',
    inputs: [
      { name: 'asset_', type: 'address', internalType: 'contract IERC20' },
      { name: 'name_', type: 'string', internalType: 'string' },
      { name: 'symbol_', type: 'string', internalType: 'string' },
      { name: 'permissionsManager_', type: 'address', internalType: 'contract PermissionsManager' },
      { name: 'maxFundingEpochsPerCall_', type: 'uint256', internalType: 'uint256' },
    ],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'isOperator',
    inputs: [
      { name: 'controller', type: 'address', internalType: 'address' },
      { name: 'operator', type: 'address', internalType: 'address' },
    ],
    outputs: [{ name: 'approved', type: 'bool', internalType: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'maxDeposit',
    inputs: [{ name: 'controller', type: 'address', internalType: 'address' }],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'maxFundingEpochsPerCall',
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'maxMint',
    inputs: [{ name: 'controller', type: 'address', internalType: 'address' }],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'maxRedeem',
    inputs: [{ name: 'controller', type: 'address', internalType: 'address' }],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'maxWithdraw',
    inputs: [{ name: 'controller', type: 'address', internalType: 'address' }],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'mint',
    inputs: [
      { name: 'shares', type: 'uint256', internalType: 'uint256' },
      { name: 'receiver', type: 'address', internalType: 'address' },
    ],
    outputs: [{ name: 'assets', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'mint',
    inputs: [
      { name: 'shares', type: 'uint256', internalType: 'uint256' },
      { name: 'receiver', type: 'address', internalType: 'address' },
      { name: 'controller', type: 'address', internalType: 'address' },
    ],
    outputs: [{ name: 'assets', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'moveCapitalIn',
    inputs: [{ name: 'assets', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'moveCapitalOut',
    inputs: [
      { name: 'assets', type: 'uint256', internalType: 'uint256' },
      { name: 'destination', type: 'address', internalType: 'address' },
    ],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'name',
    outputs: [{ name: '', type: 'string', internalType: 'string' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'nextUnfundedEpoch',
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'openEpochPendingDepositAssets',
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'pendingDepositRequest',
    inputs: [
      { name: 'requestId', type: 'uint256', internalType: 'uint256' },
      { name: 'controller', type: 'address', internalType: 'address' },
    ],
    outputs: [{ name: 'pendingAssets', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'pendingRedeemRequest',
    inputs: [
      { name: 'requestId', type: 'uint256', internalType: 'uint256' },
      { name: 'controller', type: 'address', internalType: 'address' },
    ],
    outputs: [{ name: 'pendingShares', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'permissionsManager',
    outputs: [{ name: '', type: 'address', internalType: 'contract PermissionsManager' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'previewDeposit',
    inputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'pure',
  },
  {
    type: 'function',
    name: 'previewMint',
    inputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'pure',
  },
  {
    type: 'function',
    name: 'previewRedeem',
    inputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'pure',
  },
  {
    type: 'function',
    name: 'previewWithdraw',
    inputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'pure',
  },
  {
    type: 'function',
    name: 'processFunding',
    outputs: [
      { name: 'epochsProcessed', type: 'uint256', internalType: 'uint256' },
      { name: 'bufferDebtRepaid', type: 'uint256', internalType: 'uint256' },
    ],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'proxiableUUID',
    outputs: [{ name: '', type: 'bytes32', internalType: 'bytes32' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'redeem',
    inputs: [
      { name: 'shares', type: 'uint256', internalType: 'uint256' },
      { name: 'receiver', type: 'address', internalType: 'address' },
      { name: 'controller', type: 'address', internalType: 'address' },
    ],
    outputs: [{ name: 'assets', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'redeemNative',
    inputs: [
      { name: 'shares', type: 'uint256', internalType: 'uint256' },
      { name: 'receiver', type: 'address', internalType: 'address payable' },
      { name: 'controller', type: 'address', internalType: 'address' },
    ],
    outputs: [{ name: 'assets', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'redeemReq',
    inputs: [{ name: 'controller', type: 'address', internalType: 'address' }],
    outputs: [
      { name: 'epochId', type: 'uint256', internalType: 'uint256' },
      { name: 'shares', type: 'uint256', internalType: 'uint256' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'redeemRequestsPaused',
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'reportOffchainAssets',
    inputs: [{ name: 'reportedOffchainAssets_', type: 'uint256', internalType: 'uint256' }],
    outputs: [{ name: 'closedEpochId', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'reportOffchainAssetsAndProcessFunding',
    inputs: [{ name: 'reportedOffchainAssets_', type: 'uint256', internalType: 'uint256' }],
    outputs: [
      { name: 'closedEpochId', type: 'uint256', internalType: 'uint256' },
      { name: 'epochsProcessed', type: 'uint256', internalType: 'uint256' },
      { name: 'bufferDebtRepaid', type: 'uint256', internalType: 'uint256' },
    ],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'reportedOffchainAssets',
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'requestDeposit',
    inputs: [
      { name: 'assets', type: 'uint256', internalType: 'uint256' },
      { name: 'controller', type: 'address', internalType: 'address' },
      { name: 'owner', type: 'address', internalType: 'address' },
    ],
    outputs: [{ name: 'requestId', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'requestDepositNative',
    inputs: [
      { name: 'controller', type: 'address', internalType: 'address' },
      { name: 'owner', type: 'address', internalType: 'address' },
    ],
    outputs: [{ name: 'requestId', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'requestRedeem',
    inputs: [
      { name: 'shares', type: 'uint256', internalType: 'uint256' },
      { name: 'controller', type: 'address', internalType: 'address' },
      { name: 'owner', type: 'address', internalType: 'address' },
    ],
    outputs: [{ name: 'requestId', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'reservedOnchainAssets',
    outputs: [{ name: 'reserved', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'setBuffer',
    inputs: [{ name: 'newBuffer', type: 'address', internalType: 'address' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'setDepositRequestsPaused',
    inputs: [{ name: 'paused', type: 'bool', internalType: 'bool' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'setMaxFundingEpochsPerCall',
    inputs: [{ name: 'newMaxEpochs', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'setOperator',
    inputs: [
      { name: 'operator', type: 'address', internalType: 'address' },
      { name: 'approved', type: 'bool', internalType: 'bool' },
    ],
    outputs: [{ name: 'success', type: 'bool', internalType: 'bool' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'setRedeemRequestsPaused',
    inputs: [{ name: 'paused', type: 'bool', internalType: 'bool' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'setSyntheticYield',
    inputs: [{ name: 'newSyntheticYield', type: 'address', internalType: 'address' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'share',
    outputs: [{ name: 'shareTokenAddress', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'supportsInterface',
    inputs: [{ name: 'interfaceId', type: 'bytes4', internalType: 'bytes4' }],
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
    stateMutability: 'pure',
  },
  {
    type: 'function',
    name: 'symbol',
    outputs: [{ name: '', type: 'string', internalType: 'string' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'syntheticYield',
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'totalAssets',
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'totalPendingDepositAssets',
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'totalRedeemFundedAssets',
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'totalRedeemPaidAssets',
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'totalRedeemRequiredAssets',
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'totalSupply',
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'transfer',
    inputs: [
      { name: 'to', type: 'address', internalType: 'address' },
      { name: 'value', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'transferFrom',
    inputs: [
      { name: 'from', type: 'address', internalType: 'address' },
      { name: 'to', type: 'address', internalType: 'address' },
      { name: 'value', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'upgradeToAndCall',
    inputs: [
      { name: 'newImplementation', type: 'address', internalType: 'address' },
      { name: 'data', type: 'bytes', internalType: 'bytes' },
    ],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'withdraw',
    inputs: [
      { name: 'assets', type: 'uint256', internalType: 'uint256' },
      { name: 'receiver', type: 'address', internalType: 'address' },
      { name: 'controller', type: 'address', internalType: 'address' },
    ],
    outputs: [{ name: 'shares', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'receive',
    stateMutability: 'payable',
  },
] as const
