name: Build dApp

on: pull_request

jobs:
  build_test:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
          npm run build
