name: Run e2e on Chrome

on: pull_request

# Declare default permissions as read only.
permissions: read-all

jobs:
  chrome:
    runs-on: ubuntu-22.04
    name: E2E on Chrome
    steps:
      - name: Checkout files
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2
      - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 #v6.2.0
        with:
          node-version-file: '.nvmrc'
      - name: Run Cypress end-to-end tests
        uses: cypress-io/github-action@8a35f965fbd13e3b18d9fb3bdc5f50ae2f4a5e76 #v7.1.0
        with:
          browser: chrome
          start: npm run dev