name: Trigger DAO Dapp Automation Workflow

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Other steps as needed...

      - name: Start E2E tests in target repo
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.DAO_DAPP_AUTOMATION_PAT }}
          script: |
            await github.request('POST /repos/{owner}/{repo}/actions/workflows/{workflow_id}/dispatches', {
              owner: 'rsksmart',
              repo: 'Deprecated_DAO-dApp-automation',
              workflow_id: 'playwright.yml',
              ref: 'main',
              inputs: {
                ENVIRONMENT: 'STAGING',
                TEST_TYPE: 'smoke'
              }
            });
