name: Trigger DAO Dapp Automation Workflow

on: 
  pull_request:
  workflow_dispatch:
    inputs:
      ENVIRONMENT:
        description: "Environment to run the tests in"
        required: true
        default: "CR-QA"
        type: string
      TEST_TYPE:
        description: "Type of test to run (smoke, regression)"
        required: true
        default: "smoke"
        type: string

jobs:
  trigger-e2e-tests:
    name: Trigger E2E Tests and Wait for Result
    runs-on: ubuntu-latest
    steps:
      - name: Trigger E2E Tests in Target Repo
        id: trigger
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.DAO_DAPP_AUTOMATION_PAT }}
          script: |
            const workflowDispatchResponse = await github.request('POST /repos/{owner}/{repo}/actions/workflows/{workflow_id}/dispatches', {
              owner: 'rsksmart',
              repo: 'Deprecated_DAO-dApp-automation',
              workflow_id: 'playwright.yml',
              ref: 'main',
              inputs: {
                ENVIRONMENT: 'CR-QA',
                TEST_TYPE: 'smoke'
              }
            });

            const now = new Date().toISOString();
            core.setOutput("trigger_time", now);

      - name: Wait for workflow to be registered
        run: sleep 15

      - name: Get Workflow Run ID
        id: get_run
        run: |
          echo "Looking for matching workflow run..."
          TRIGGER_TIME="${{ steps.trigger.outputs.trigger_time }}"

          RUN_INFO=$(curl -s -H "Authorization: Bearer ${{ secrets.DAO_DAPP_AUTOMATION_PAT }}" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/rsksmart/Deprecated_DAO-dApp-automation/actions/workflows/playwright.yml/runs?event=workflow_dispatch&branch=main&per_page=5")

          RUN_ID=$(echo "$RUN_INFO" | jq -r --arg TIME "$TRIGGER_TIME" '
            .workflow_runs
            | map(select(.created_at > $TIME))
            | sort_by(.created_at)
            | last
            | .id')

          if [ "$RUN_ID" = "null" ] || [ -z "$RUN_ID" ]; then
            echo "❌ Could not find the triggered workflow run."
            exit 1
          fi

          echo "Found workflow run ID: $RUN_ID"
          echo "run_id=$RUN_ID" >> $GITHUB_OUTPUT

      - name: Poll workflow status
        run: |
          RUN_ID=${{ steps.get_run.outputs.run_id }}

          echo "Polling run ID: $RUN_ID"
          STATUS=""
          CONCLUSION=""

          until [ "$STATUS" = "completed" ]; do
            sleep 15

            RESPONSE=$(curl -s -H "Authorization: Bearer ${{ secrets.DAO_DAPP_AUTOMATION_PAT }}" \
              -H "Accept: application/vnd.github+json" \
              "https://api.github.com/repos/rsksmart/Deprecated_DAO-dApp-automation/actions/runs/$RUN_ID")

            STATUS=$(echo "$RESPONSE" | jq -r '.status')
            CONCLUSION=$(echo "$RESPONSE" | jq -r '.conclusion')
            echo "Status: $STATUS, Conclusion: $CONCLUSION"
          done

          if [ "$CONCLUSION" != "success" ]; then
            echo "❌ E2E tests failed."
            exit 1
          else
            echo "✅ E2E tests passed!"
          fi
